version: '3'
services:
  ssr-backend:
    build: .
    command:
      - python
      - ssr/shadowsocks/server.py
      - -c
      - /etc/shadowsocksr.json
    volumes:
      - ./shadowsocksr.json:/etc/shadowsocksr.json
    ports:
      - 12345:12345
